## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
googleAnalytics = "G-BHCVSYXKXM"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Foley Stoneworks creates handcrafted stonework and masonry with a focus on traditional craftsmanship and timeless design."
  logo = "images/crossed-hammers.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "email@email.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"
  phone = "XXXXXXXXXX"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]